### ISSUE TITLE
Search speed elementor intégration 

### ISSUE THREAD

**Issue by neosaveme** [FacetWP/roadmap#37]
hello ,
I have an important note of improvement / optimization I noticed this problem almost a year ago, but I did not pay attention thinking that it would be solved on its own..
but today 
I realize that all my work depends on this simple detail, the efficiency of research and the speed.

I'm talking about "Plugin Elementor Integration facetwp" 
and even others plugins that support facetwp like jetengine 

as I am creating a real estate site, I realized that the loading search times are very very slow and very different between elementor/jetengine template and facetwp layourt builder template ,  we easily exceed 5,10,15+ seconds..

elementor is very user-friendly and powerful to create listings/loops as we like, but Elementor Integration facetwp makes it usless in terms of speed.. 

on the other side facetwp it's great but your layourt builder is out of play against elementor..

to illustrate the problem I have attached an image that explains everything. 
tested with jetengine but also with your elementor integration plugin the results are the same **https://ibb.co/SnKCNsg**

I hope that someone in your team will dig into the problem and understand what is going on with elementor templates and why one is almost instantaneous and the other is struggling to display the result.

what I thought was to change the tactic and add support for an elementor template shortcode in this way we use our loop templates already created and ready to use, but of course the loading times must be similar.

or integrate elementor as loop editor

it's been a year i don't understand what's going on, can you check why it's slow?

**Comment by mgibbs189** [comment]
@neosaveme this Issue tracker is intended for **internal** use. Please open a support ticket if you have any specific concerns.
